version: '2'
services:
    api-app:
        image: api
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://api-postgresql:5432/api
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=api-elasticsearch:9300
    api-postgresql:
        extends:
            file: postgresql.yml
            service: api-postgresql
    api-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: api-elasticsearch
